#!/usr/bin/env bash
#
# Cloudflare Tunnel Setup for Regular Sandbox
#
# Sets up a Cloudflare tunnel (cloudflared) to expose sandbox SSH
# to the internet without requiring specific network configuration.
#
# Prerequisites:
#   - cloudflared installed
#   - Cloudflare Zero Trust account with a tunnel created
#   - Tunnel credentials file
#
# Usage:
#   cloudflare-tunnel-setup.sh configure <tunnel-token>
#   cloudflare-tunnel-setup.sh start
#   cloudflare-tunnel-setup.sh start-ssh <tunnel-name>
#

set -euo pipefail

TUNNEL_CONFIG_DIR="${HOME}/.cloudflare-tunnel"
TUNNEL_NAME="${TUNNEL_NAME:-sandbox-ssh-tunnel}"
TUNNEL_SSH_PORT="${TUNNEL_SSH_PORT:-2222}"
TUNNEL_API_URL="${TUNNEL_API_URL:-http://daytona-api:3000}"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

error() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $*" >&2
    exit 1
}

check_dependencies() {
    if ! command -v cloudflared &>/dev/null; then
        error "cloudflared not found. Install: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/"
    fi
}

configure_tunnel() {
    local token="${1:-}"
    [[ -z "$token" ]] && error "Usage: $0 configure <tunnel-token>"

    mkdir -p "${TUNNEL_CONFIG_DIR}"

    log "Authenticating tunnel..."
    cloudflared service install "${token}" --directory "${TUNNEL_CONFIG_DIR}"

    log "Tunnel configured successfully!"
    log "Config directory: ${TUNNEL_CONFIG_DIR}"
}

start_tunnel() {
    check_dependencies

    mkdir -p "${TUNNEL_CONFIG_DIR}"

    log "Starting Cloudflare tunnel..."
    log "Tunnel name: ${TUNNEL_NAME}"
    log "SSH port: ${TUNNEL_SSH_PORT}"

    cloudflared tunnel run \
        --token "${CLOUDFLARED_TUNNEL_TOKEN}" \
        --name "${TUNNEL_NAME}" \
        --url "http://localhost:${TUNNEL_SSH_PORT}" \
        --logfile "${TUNNEL_CONFIG_DIR}/tunnel.log" \
        --metrics "localhost:53121"

    log "Tunnel started"
}

start_ssh_tunnel() {
    local tunnel_name="${1:-${TUNNEL_NAME}}"

    check_dependencies

    log "Starting SSH-over-Cloudflare tunnel..."

    cloudflared access tcp \
        --hostname "ssh-${tunnel_name}.${CLOUDFLARE_DOMAIN}" \
        --url "tcp://localhost:${TUNNEL_SSH_PORT}" \
        --logfile "${TUNNEL_CONFIG_DIR}/ssh-tunnel.log"

    log "SSH tunnel started"
}

setup_ssh_config() {
    local hostname="${1:-}"
    [[ -z "$hostname" ]] && error "Usage: $0 setup-ssh <cloudflare-hostname>"

    local ssh_config_file="${HOME}/.ssh/config.d/cloudflare-sandbox.conf"

    mkdir -p "$(dirname "${ssh_config_file}")"

    cat > "${ssh_config_file}" << EOF
# Cloudflare Sandbox SSH Configuration
# Auto-generated by cloudflare-tunnel-setup.sh

Host cloudflare-sandbox
    HostName ${hostname}
    Port 22
    User daytona
    IdentityFile ~/.ssh/id_ed25519
    StrictHostKeyChecking no
    UserKnownHostsFile ~/.ssh/known_hosts
    ProxyCommand cloudflared access tcp --hostname %h --url tcp://localhost:2222
EOF

    log "SSH config written to: ${ssh_config_file}"
}

show_status() {
    if [[ -f "${TUNNEL_CONFIG_DIR}/tunnel.log" ]]; then
        log "Tunnel log:"
        tail -20 "${TUNNEL_CONFIG_DIR}/tunnel.log"
    else
        log "No tunnel log found. Tunnel may not be running."
    fi
}

main() {
    local command="${1:-}"

    case "${command}" in
        configure)
            configure_tunnel "${2:-}"
            ;;
        start)
            start_tunnel
            ;;
        start-ssh)
            start_ssh_tunnel "${2:-}"
            ;;
        setup-ssh)
            setup_ssh_config "${2:-}"
            ;;
        status)
            show_status
            ;;
        *)
            echo "Usage: $0 {configure|start|start-ssh|setup-ssh|status}"
            echo ""
            echo "Commands:"
            echo "  configure <token>    - Configure tunnel with auth token"
            echo "  start                - Start the tunnel"
            echo "  start-ssh [name]     - Start SSH tunnel"
            echo "  setup-ssh <hostname>  - Generate SSH config for tunnel"
            echo "  status               - Show tunnel status"
            exit 1
            ;;
    esac
}

main "$@"
