#!/usr/bin/env python3
"""
Daytona Sandbox SSH Wrapper Script

Provides seamless SSH access to Daytona sandbox environments.
Run after SSH config is set up in .ssh folder.

Usage:
    ssh daytona-sandbox          # Connect to default sandbox
    ssh daytona-sandbox -p 2222 # Connect with specific port
"""

import argparse
import os
import sys
import subprocess
from pathlib import Path

DAYTONA_SSH_CONFIG = """
# Daytona Sandbox SSH Configuration
# Auto-generated by ssh-daytona-wrapper

Host daytona-sandbox
    HostName 127.0.0.1
    Port {port}
    User daytona
    IdentityFile {identity_file}
    StrictHostKeyChecking no
    UserKnownHostsFile {known_hosts}
    ProxyCommand {proxy_command}
"""

DEFAULT_DAYTONA_TARGET = os.environ.get("DAYTONA_TARGET", "us")
DEFAULT_DAYTONA_API_URL = os.environ.get("DAYTONA_API_URL", "http://daytona-api:3000/api")


def get_ssh_dir() -> Path:
    return Path.home() / ".ssh"


def get_daytona_config_path() -> Path:
    return get_ssh_dir() / "config.d" / "daytona-sandbox.conf"


def ensure_ssh_config_dir():
    config_dir = get_ssh_dir() / "config.d"
    config_dir.mkdir(parents=True, exist_ok=True)


def configure_ssh(
    host: str = "127.0.0.1",
    port: int = 2222,
    identity_file: str = "~/.ssh/id_ed25519",
    known_hosts: str = "~/.ssh/known_hosts",
    proxy_command: str = "",
):
    """Configure SSH for Daytona sandbox access."""
    ensure_ssh_config_dir()

    config_path = get_daytona_config_path()

    proxy_cmd = f"ssh -W %h:%p daytona-tunnel" if proxy_command else ""

    config = DAYTONA_SSH_CONFIG.format(
        port=port,
        identity_file=identity_file,
        known_hosts=known_hosts,
        proxy_command=proxy_cmd or proxy_command,
    )

    config_path.write_text(config)
    print(f"SSH config written to: {config_path}")


def connect_to_sandbox(
    sandbox_id: str | None = None,
    user: str = "daytona",
    port: int = 2222,
    identity_file: str = "~/.ssh/id_ed25519",
):
    """Establish SSH connection to Daytona sandbox."""
    cmd = [
        "ssh",
        "-o", "StrictHostKeyChecking=no",
        "-o", "UserKnownHostsFile=/dev/null",
        "-p", str(port),
        "-i", os.path.expanduser(identity_file),
    ]

    if sandbox_id:
        cmd.append(f"{user}@{sandbox_id}")
    else:
        cmd.append(user)

    try:
        subprocess.run(cmd)
    except KeyboardInterrupt:
        pass
    except Exception as e:
        print(f"Connection failed: {e}", file=sys.stderr)
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description="Daytona Sandbox SSH Wrapper",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    ssh-daytona-wrapper configure --port 2222
    ssh-daytona-wrapper connect
    ssh-daytona-wrapper connect --user admin --sandbox-id abc123
        """,
    )

    subparsers = parser.add_subparsers(dest="command", required=True)

    configure_parser = subparsers.add_parser("configure", help="Configure SSH for Daytona sandbox")
    configure_parser.add_argument("--host", default="127.0.0.1", help="Sandbox host")
    configure_parser.add_argument("--port", type=int, default=2222, help="SSH port")
    configure_parser.add_argument("--identity-file", default="~/.ssh/id_ed25519", help="SSH identity file")
    configure_parser.add_argument("--known-hosts", default="~/.ssh/known_hosts", help="Known hosts file")
    configure_parser.add_argument("--proxy-command", default="", help="Proxy command for tunnel")

    connect_parser = subparsers.add_parser("connect", help="Connect to sandbox via SSH")
    connect_parser.add_argument("--sandbox-id", help="Sandbox ID to connect to")
    connect_parser.add_argument("--user", default="daytona", help="SSH user")
    connect_parser.add_argument("--port", type=int, default=2222, help="SSH port")
    connect_parser.add_argument("--identity-file", default="~/.ssh/id_ed25519", help="SSH identity file")

    args = parser.parse_args()

    if args.command == "configure":
        configure_ssh(
            host=args.host,
            port=args.port,
            identity_file=args.identity_file,
            known_hosts=args.known_hosts,
            proxy_command=args.proxy_command,
        )
    elif args.command == "connect":
        connect_to_sandbox(
            sandbox_id=args.sandbox_id,
            user=args.user,
            port=args.port,
            identity_file=args.identity_file,
        )


if __name__ == "__main__":
    main()
